<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKLg0qFf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKLg0qFf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKLg0qFf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKLg0qFf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKLg0qFf\App_KernelDevDebugContainer([
    'container.build_hash' => 'KLg0qFf',
    'container.build_id' => 'fda34a3d',
    'container.build_time' => 1714464397,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKLg0qFf');
